### ISSUE TITLE
Podcast GB block does not load or play file on WP 5.3.2

### ISSUE THREAD

**Issue by Waka867** [10up/simple-podcasting#81] opened 2020-01-13 16:44 UTC
**Describe the bug**
On post view, preview, and blog listing pages, gutenberg podcast block does not play, no console errors shown. Time shows 0:00/0:00 and podcast doesn't load, file plays when added on the edit page. Adding conventional audio block works fine. Server php/apache error logs show no errors on day or even week of test. Tried checking what was referenced [here](https://github.com/10up/simple-podcasting/issues/46#issuecomment-434408525) and found the same situation: adding an audio file block has the correct <audio> src and other tags but the podcast block does not.

**Steps to Reproduce**

1. Go to simple podcast plugin admin page
2. Add new podcast
3. Create a new post
4. Add new podcast block
5. Add or upload podcast file (here the podcast file should play correctly)
6. Add new audio block
7. add or upload audio file
8. In right hand side menu click document, then under podcasts dropdown assign to your created podcast
9. Click Update at the top right
10. Click view post at the top of the page
11. Audio block should play correctly while podcast block does not.

**Expected behavior**
Podcast block should load and play file much like how the audio block does

**Screenshots**
![Annotation 2020-01-13 113832 - simple podcasting issue](https://user-images.githubusercontent.com/10965317/72274118-91f36e00-35f9-11ea-9030-fbcfa03dc6dd.png)
![Annotation 2020-01-13 113933 simple podcasting issue b](https://user-images.githubusercontent.com/10965317/72274158-a0418a00-35f9-11ea-898e-8c253dfbd7e0.png)

**Environment information**
 - Device: Dell Desktop
 - OS: Windows 10  v.1809
 - Browser and version: Chrome 79.0.3945.117
 - Plugins and version: 
 - Theme and version: TwentyTwenty 1.0
 - Other installed plugin(s) and version(s):

**Additional context**
Information from site health

### wp-core ###

version: 5.3.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: C:\wamp64\www\simple-podcasting-testing
wordpress_size: 37.84 MB (39681240 bytes)
uploads_path: C:\wamp64\www\simple-podcasting-testing/wp-content/uploads
uploads_size: 8.67 MB (9088125 bytes)
themes_path: C:\wamp64\www\simple-podcasting-testing/wp-content/themes
themes_size: 4.64 MB (4860942 bytes)
plugins_path: C:\wamp64\www\simple-podcasting-testing/wp-content/plugins
plugins_size: 436.91 KB (447399 bytes)
database_size: 708.89 KB (725901 bytes)
total_size: 52.26 MB (54803607 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.0 (latest version: 1.1)
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: C:\wamp64\www\simple-podcasting-testing/wp-content/themes/twentytwenty

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.4, author: the WordPress team
Twenty Seventeen: version: 2.2, author: the WordPress team
Twenty Sixteen: version: 2.0, author: the WordPress team

### wp-plugins-active (1) ###

Simple Podcasting: version: 1.1.1, author: 10up

### wp-plugins-inactive (2) ###

Akismet Anti-Spam: version: 4.1.3, author: Automattic
Hello Dolly: version: 1.7.2, author: Matt Mullenweg

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.39 (Win64) PHP/7.2.18
php_version: 7.2.18 64bit
php_sapi: apache2handler
max_input_variables: 2500
time_limit: 120
memory_limit: 256M
max_input_time: 60
upload_max_size: 2M
php_post_max_size: 8M
curl_version: 7.64.0 OpenSSL/1.1.1b
suhosin: false
imagick_availability: false
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 5.7.26
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: C:\wamp64\www\simple-podcasting-testing/wp-content
WP_PLUGIN_DIR: C:\wamp64\www\simple-podcasting-testing/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

**Comment by jeffpaul** [comment] 2020-01-17 02:38
Thanks for the testing and bug report @Waka867!  I've milestoned this issue for our next minor release.  If you're able to work on a PR to resolve this, then I'd gladly get it through review and into the release.  Thanks again!

**Comment by dinhtungdu** [comment] 2020-01-20 09:52
Tested this issue today:
- The issue occurs if we add a new post > add a podcast block > Select a podcast from the library > Save > Reload the browser > See the empty podcast block.
- Then we select a podcast for that empty block above > Save > Reload > See the block with the selected podcast > No Error 🤨
- There is another way to reproduce this issue is: add a new post > add a podcast block > Select a podcast from the library > hit `⇧⌥⌘M` see the empty podcast block as in code editor > hit `⇧⌥⌘M` again, see the podcast block as the screenshot above.
- I tested with the master version of Gutenberg, then no error occurs 🧐except an issue in our `Edit` component (see: https://github.com/10up/simple-podcasting/blob/develop/assets/js/edit.js#L36-L46) which remove the podcast id when switching between block and code editor.

**Comment by dinhtungdu** [comment] 2020-01-20 13:01
Update: some time in my test, click on `Media Library` button > I can choose all media types, not just `audio` as expected.
Update: after build the js file again, the media library issue is fixed.

**Comment by jeffpaul** [comment] 2020-01-22 14:46
If I'm understanding this correctly, it sounds like the latest version of Gutenberg resolves this issue.  Which means the next major release of WP 5.4 that bundles this Gutenberg version should ensure things are back functioning as expected.  If that's accurate, then we may just let this ride until March 31st when WP 5.4 is scheduled to be released.  We'll want to test against the betas/RCs for 5.4 to see that things work as expected then.

In terms of being able to select more than just `audio` files for the podcast block, that should probably be in a separate issue that we can address with a related PR.  @dinhtungdu, if I'm understanding your test results accurately, could you open that issue please?  If I'm not understanding things, could you please clarify?  Thanks!

**Comment by dinhtungdu** [comment] 2020-01-22 15:02
> In terms of being able to select more than just audio files for the podcast block, that should probably be in a separate issue that we can address with a related PR

@jeffpaul This issue has been fixed with #77. I had that issue because the dist files didn't get rebuilt in #77, that PR only updated the source file.

**Comment by jeffpaul** [comment] 2020-04-30 01:12
@Waka867 with WP 5.4 released, can you re-test this scenario to see if this issue still exists with Simple Podcasting and WordPress 5.4?

**Comment by Waka867** [comment] 2020-04-30 13:35
Yes, I just might not be able to get to it today.

> @Waka867 with WP 5.4 released, can you re-test this scenario to see if this issue still exists with Simple Podcasting and WordPress 5.4?

**Comment by Waka867** [comment] 2020-05-26 16:00
Sorry, just to update I will likely not be able to get to this. I'm working remotely for an essential company that is getting slammed.

**Comment by jeffpaul** [comment] 2020-06-03 03:40
@Waka867 no problem, stay safe!

**Comment by helen** [comment] 2020-07-08 22:17
This seems fixed to me as of WP 5.4.2.

**Closed as completed by helen** 2020-07-08 22:17 UTC
Labels: type:bug, help wanted, resolution:wontfix, needs:feedback
